name: PaperBlockTuner
version: 1.2.0
main: io.github.lumine1909.blocktuner.BlockTunerPlugin
libraries:
  - org.reflections:reflections:0.10.2
  - org.xerial:sqlite-jdbc:3.49.1.0
api-version: 1.21
authors:
  - Lumine1909